# -*- coding: utf-8 -*-
"""python list manipulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hE2EOYMxbMBt5P-GPPwIVEMbtH2hAwFq
"""

class ListManipulator:
    def __init__(self):
        self.internal_list = []

    def add_elements(self, elements):
        self.internal_list.extend(elements)

    def remove_duplicates(self):
        self.internal_list = list(set(self.internal_list))

    def reverse_list(self):
        self.internal_list.reverse()

    def sort_list(self):
        self.internal_list.sort()

    def get_unique_elements(self):
        return list(set(self.internal_list))

    def remove_element(self, element):
        if element in self.internal_list:
            self.internal_list.remove(element)

    def get_list(self):
        return self.internal_list

# Example usage:
manipulator = ListManipulator()
manipulator.add_elements([1, 2, 3, 4, 2, 3])
print("Original list:", manipulator.get_list())

manipulator.remove_duplicates()
print("List after removing duplicates:", manipulator.get_list())

manipulator.reverse_list()
print("Reversed list:", manipulator.get_list())

manipulator.sort_list()
print("Sorted list:", manipulator.get_list())

print("Unique elements:", manipulator.get_unique_elements())

manipulator.remove_element(3)
print("List after removing element 3:", manipulator.get_list())